name: Generate Snake Animation

on:
  schedule:
    # Обновление каждый час
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AnnAlekh
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push the animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

